#!/bin/bash

# Upload BAR file to Artifactory

ARTIFACTORY_HOST=$1
ARTIFACTORY_REPO=$2
ARTIFACTORY_GROUP=$3
ARTIFACTORY_BAR_NAME=$4
ARTIFACTORY_VERSION=$5
ARTIFACTORY_USER=$6
ARTIFACTORY_PASSWORD=$7

echo "curl -v -u $ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD - X POST http://$ARTIFACTORY_HOST/service/rest/v1/components?repository=$ARTIFACTORY_REPO"
curl -v -u $ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD -X POST http://$ARTIFACTORY_HOST/service/rest/v1/components?repository=$ARTIFACTORY_REPO -F maven2.groupId=$ARTIFACTORY_GROUP -F maven2.artifactId=$ARTIFACTORY_BAR_NAME -F maven2.version=$ARTIFACTORY_VERSION -F maven2.asset1=@$ARTIFACTORY_BAR_NAME.bar -F maven2.asset1.extension=bar